// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxkuS2oIS8SPv70G8L0rgt5jyrZJHosU',
    appId: '1:165962374711:web:70311a5f739bd82ed4a9b2',
    messagingSenderId: '165962374711',
    projectId: 'toko-pintar-mobile',
    authDomain: 'toko-pintar-mobile.firebaseapp.com',
    storageBucket: 'toko-pintar-mobile.firebasestorage.app',
    measurementId: 'G-G17VWVYZVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdtm09cMHLsXCNGjFIteXxwWsf-8VMgg',
    appId: '1:165962374711:android:81bb88f894e95eadd4a9b2',
    messagingSenderId: '165962374711',
    projectId: 'toko-pintar-mobile',
    storageBucket: 'toko-pintar-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZX7Ktaz8BpFcDsCPt3-p7muWNxIpwMoY',
    appId: '1:165962374711:ios:e8fbb58a6f896898d4a9b2',
    messagingSenderId: '165962374711',
    projectId: 'toko-pintar-mobile',
    storageBucket: 'toko-pintar-mobile.firebasestorage.app',
    iosBundleId: 'com.example.mobilePintar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZX7Ktaz8BpFcDsCPt3-p7muWNxIpwMoY',
    appId: '1:165962374711:ios:e8fbb58a6f896898d4a9b2',
    messagingSenderId: '165962374711',
    projectId: 'toko-pintar-mobile',
    storageBucket: 'toko-pintar-mobile.firebasestorage.app',
    iosBundleId: 'com.example.mobilePintar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJxkuS2oIS8SPv70G8L0rgt5jyrZJHosU',
    appId: '1:165962374711:web:6aa2898aef37cf1bd4a9b2',
    messagingSenderId: '165962374711',
    projectId: 'toko-pintar-mobile',
    authDomain: 'toko-pintar-mobile.firebaseapp.com',
    storageBucket: 'toko-pintar-mobile.firebasestorage.app',
    measurementId: 'G-VPECVMDJFS',
  );
}
